#Q1. What is the total revenue generated by male vs female customers?
select gender ,sum(purchase_amount) as revenue from customer group by gender;

---------------------------------------------------------------------------------

# Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount from customer 
where discount_applied ='Yes'and purchase_amount >=(select avg(purchase_amount ));

-------------------------------------------------------------------------------------------
# Q3. Which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS 'Average product rating'
FROM
    customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

------------------------------------------------------------------------------------------

# Q4. Compare the average purchase amounts between standard and express shipping.
SELECT 
    shipping_type, AVG(purchase_amount)
FROM
    customer
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type
ORDER BY AVG(purchase_amount) ASC;

---------------------------------------------------------------------------------------------------------------
#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non.

select subscription_status,
count(customer_id) as total_customers, 
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue from customer
group by subscription_status 
order by total_revenue, avg_spend desc;

------------------------------------------------------------------------------------------------------------------------
# Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND((SUM(CASE
    WHEN discount_applied = 'Yes' THEN 1
    ELSE 0
  END) / COUNT(*)) * 100,
2) AS discount_rate
FROM
    customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;

-----------------------------------------------------------------------------------------------------------------------------

#Q7. Segment customers into new ,returning and loyal based on their total previous purchases.
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-------------------------------------------------------------------------------------------------------------
#Q8. What are the top 3 most purchased products within each category.

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

---------------------------------------------------------------------------------------------------------

# Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers from customer
where previous_purchases > 5
group by subscription_status
;

-------------------------------------------------------------------------------------------------------------------

#Q10. What is the revenue contribution of each age group ?

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

---------------------------------------------------------------------------------------------------------------------------
